max_width = 128
tab_spaces = 4

unstable_features = true

use_small_heuristics = "Off"
array_width = 60
attr_fn_like_width = 70
chain_width = 60
comment_width = 96
fn_call_width = 60
doc_comment_code_block_width = 128
inline_attribute_width = 100
single_line_if_else_max_width = 50
single_line_let_else_max_width = 50
struct_lit_width = 18
struct_variant_width = 35
short_array_element_width_threshold = 10

enum_discrim_align_threshold = 64
struct_field_align_threshold = 64

fn_params_layout = "Tall"
fn_single_line = true

imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true
skip_children = false


binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "PreferSameLine"
color = "Auto"
combine_control_expr = true
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
empty_item_single_line = true

error_on_line_overflow = false
error_on_unformatted = false

force_explicit_abi = true
force_multiline_blocks = false
format_code_in_doc_comments = true
format_generated_files = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
hard_tabs = false
hex_literal_case = "Upper"
hide_parse_errors = false

imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
match_arm_blocks = true
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
merge_derives = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true

space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_lit_single_line = false

trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"

use_field_init_shorthand = false
use_try_shorthand = true

where_single_line = false
wrap_comments = false
