[package]
name = "nd-libr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nd-algorithms = { path = "ext/algorithms" }
nd-colors = { path = "ext/colors" }
nd-core = { path = "ext/core" }

[dev-dependencies]
criterion = "0"
