[package]
name = "nd-libr"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["ext/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.lints.rust]
[workspace.lints.clippy]

[workspace.dependencies]
anyhow = "1"
thiserror = "1"

rayon = "1"
tokio = "1"
tracing = "0"

criterion = "0"

nd-algorithms = { path = "ext/algorithms" }
nd-core = { path = "ext/core" }
nd-hash = { path = "ext/hash" }
nd-prime = { path = "ext/prime" }

[dependencies]
nd-algorithms.workspace = true
nd-core.workspace = true
nd-hash.workspace = true
nd-prime.workspace = true
