[package]
name = "nd-libr"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["ext/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1"
thiserror = "1"

rayon = "1"
tokio = "1"
tracing = "0"

criterion = "0"

nd-algorithms = { path = "ext/algorithms" }
nd-colors = { path = "ext/colors" }
nd-core = { path = "ext/core" }

[dependencies]
nd-algorithms.workspace = true
nd-colors.workspace = true
nd-core.workspace = true
