[package]
name = "nd-core"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lints]
workspace = true

[features]
default = ["num", "ops"]
num = []
ops = []
